apiVersion: v1
kind: ConfigMap
metadata:
  name: incrementer-app-redis-ha-probes
  namespace: jobleads-test-ha
  labels:
    app: jobleads-test-ha
    component: redis-ha
    version: 5.0.6-alpine
data:
  liveness.sh: |+
    #!/bin/sh
    set -eu
    CHECK_SERVER="$(redis-cli -p "$1" -a "$AUTH" ping)"
  
    if [ "$CHECK_SERVER" != "PONG" ] && [ "$CHECK_SERVER" != "LOADING Redis is loading the dataset in memory" ]; then
        echo "Server check failed with: $CHECK_SERVER"
        exit 1
    fi
  
  readiness.sh: |+
    #!/bin/sh
    set -eu
    CHECK_SERVER="$(redis-cli -p "$1" -a "$AUTH" ping)"
  
    if [ "$CHECK_SERVER" != "PONG" ] && [ "$CHECK_SERVER" != "LOADING Redis is loading the dataset in memory" ]; then
        echo "Server check failed with: $CHECK_SERVER"
        exit 1
    fi
  check-quorum.sh: |
    #!/bin/sh
    set -eu
    MASTER_GROUP="redis-ha"
    SENTINEL_PORT=26379
    REDIS_PORT=6379
    NUM_SLAVES=$(redis-cli -p "$SENTINEL_PORT" sentinel master redis-ha | awk '/num-slaves/{getline; print}')
    MIN_SLAVES=1

    if [ "$1" = "$SENTINEL_PORT" ]; then
        if redis-cli -p "$SENTINEL_PORT" sentinel ckquorum "$MASTER_GROUP" | grep -q NOQUORUM ; then
            echo "ERROR: NOQUORUM. Sentinel quorum check failed, not enough sentinels found"
            exit 1
        fi
    elif [ "$1" = "$REDIS_PORT" ]; then
        if [ "$MIN_SLAVES" -gt "$NUM_SLAVES" ]; then
            echo "Could not find enough replicating slaves. Needed $MIN_SLAVES but found $NUM_SLAVES"
            exit 1
        fi
    fi
    sh /probes/readiness.sh "$1"
