apiVersion: v1
kind: Service
metadata:
  name: counter-app
  namespace: jobleads-test-ha
  labels:
    app: jobleads-test-ha
    component: counter-app
    version: v0.0.1-debian-buster-slim
spec:
  type: LoadBalancer
  loadBalancerIP: 34.65.209.78
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: jobleads-test-ha
    component: counter-app
    version: v0.0.1-debian-buster-slim
