apiVersion: v1
kind: Service
metadata:
  name: incrementer-app-redis-ha-announce-0
  namespace: jobleads-test-ha
  labels:
    app: jobleads-test-ha
    component: redis-ha
    version: 5.0.6-alpine
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    app: jobleads-test-ha
    component: redis-ha
    version: 5.0.6-alpine
    "statefulset.kubernetes.io/pod-name": incrementer-app-redis-ha-server-0
