apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  namespace: jobleads-test
  labels:
    app: jobleads-test
    component: counter-app
    version: v0.0.1-debian-buster-slim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jobleads-test
      component: counter-app
      version: v0.0.1-debian-buster-slim
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jobleads-test
        component: counter-app
        version: v0.0.1-debian-buster-slim
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: jobleads-test
                  component: counter-app
                  version: v0.0.1-debian-buster-slim
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
      - name: counter-app-regcred
      containers:
      - name: counter-app
        image: docker.pkg.github.com/caermeglaeddyv/jobleads-test/counter-app:0.0.1-debian-buster-slim
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: counter-app-redis-server
        ports:
        - name: http
          containerPort: 8080
