{{- if not .Values.imagePullSecrets.existing -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "counter-app.fullname" . }}-regcred
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "counter-app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.regcred | b64enc }}
{{- end -}}
