{{- if and .Values.rbac.enabled .Values.psp.enabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "counter-app.fullname" . }}
  labels:
    {{- include "counter-app.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
spec:
  allowPrivilegeEscalation: false
  forbiddenSysctls:
  - '*'
  requiredDropCapabilities:
  - ALL
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  volumes:
  - configMap
  - secret
  allowedHostPaths:
  - pathPrefix: {{ .Values.logging.hostPath }}
    readOnly: false
{{- end -}}
