{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "counter-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "counter-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "counter-app.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "counter-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
